// Mocks generated by Mockito 5.4.6 from annotations
// in amplify_auth/test/core/services/auth_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:amplify_auth/core/services/auth_service.dart' as _i3;
import 'package:amplify_flutter/amplify_flutter.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSignUpResult_0 extends _i1.SmartFake implements _i2.SignUpResult {
  _FakeSignUpResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSignInResult_1 extends _i1.SmartFake implements _i2.SignInResult {
  _FakeSignInResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResetPasswordResult_2 extends _i1.SmartFake
    implements _i2.ResetPasswordResult {
  _FakeResetPasswordResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.SignUpResult> signUp(
    String? email,
    String? password,
    String? firstName,
    String? familyName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUp,
          [
            email,
            password,
            firstName,
            familyName,
          ],
        ),
        returnValue: _i4.Future<_i2.SignUpResult>.value(_FakeSignUpResult_0(
          this,
          Invocation.method(
            #signUp,
            [
              email,
              password,
              firstName,
              familyName,
            ],
          ),
        )),
      ) as _i4.Future<_i2.SignUpResult>);

  @override
  _i4.Future<_i2.SignUpResult> confirmSignUp(
    String? email,
    String? confirmationCode,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmSignUp,
          [
            email,
            confirmationCode,
          ],
        ),
        returnValue: _i4.Future<_i2.SignUpResult>.value(_FakeSignUpResult_0(
          this,
          Invocation.method(
            #confirmSignUp,
            [
              email,
              confirmationCode,
            ],
          ),
        )),
      ) as _i4.Future<_i2.SignUpResult>);

  @override
  _i4.Future<_i2.SignInResult> signIn(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [
            email,
            password,
          ],
        ),
        returnValue: _i4.Future<_i2.SignInResult>.value(_FakeSignInResult_1(
          this,
          Invocation.method(
            #signIn,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i4.Future<_i2.SignInResult>);

  @override
  _i4.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> resendVerificationCode(String? email) => (super.noSuchMethod(
        Invocation.method(
          #resendVerificationCode,
          [email],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i2.ResetPasswordResult> resetPassword(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [email],
        ),
        returnValue: _i4.Future<_i2.ResetPasswordResult>.value(
            _FakeResetPasswordResult_2(
          this,
          Invocation.method(
            #resetPassword,
            [email],
          ),
        )),
      ) as _i4.Future<_i2.ResetPasswordResult>);

  @override
  _i4.Future<_i2.ResetPasswordResult> confirmResetPassword(
    String? email,
    String? newPassword,
    String? code,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmResetPassword,
          [
            email,
            newPassword,
            code,
          ],
        ),
        returnValue: _i4.Future<_i2.ResetPasswordResult>.value(
            _FakeResetPasswordResult_2(
          this,
          Invocation.method(
            #confirmResetPassword,
            [
              email,
              newPassword,
              code,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ResetPasswordResult>);

  @override
  _i4.Future<void> updatePassword({
    required String? oldPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePassword,
          [],
          {
            #oldPassword: oldPassword,
            #newPassword: newPassword,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
